### PR TITLE
Add Trello service

### PR DESCRIPTION
**Pull request by zaosoula**

### CODE REVIEW

**Comment by saenzramiro** [comment]
AFAIK Trello don't have a chat feature. Am I wrong?

**Comment by zarque** [comment]
Yes, but it is the missing tools at our Team in Rambox, that's why I think to add this at Rambox

**Comment by bendikl** [comment]
Guys if we`re adding tools where the Rambox implementation does NOT centralize around chat or notifications, it will make rambox become an browser tab application. Be careful watering out the concept of rambox.

On the other hand Trello revolves alot around notifications and actions related to this, how could we for example implement the trello notification / messages stream?

**Comment by bendikl** [comment]
I might step back on what I said earlier, if the broader perspective of Rambox will change towards web apps in general (whom I think is quite useful if it can be ram/memory effective) then this is a useful addon.

**Comment by YesThatAllen** [comment]
I added Trello as a custom service before I saw this PR, and it's very helpful to get the notifications of colleagues' work as it happens. I support this PR.

**Comment by angelopolotto** [comment]
I tried to add a custom service for Trello but i could not login. Trello blocked the login because of certification problem.

**Comment by saenzramiro** [comment]
Ok, I will plan to add Trello in next version.

@angelopolotto Please update to version 0.5.3 and try again.

**Comment by angelopolotto** [comment]
@saenzramiro i updated here, it's everything OK. Thanks.

**Comment by chrillep** [comment]
every card is similar to a chat anyways?

**Comment by kojimairiguchi** [comment]
Do you have any notice about this addon??

**Comment by tiagolab360** [comment]
Will this be merged  ?

**Comment by heber-junior** [comment]
I added Trello as a custom service. It's ok for me.

**Pull request closed without merging**
