### PR TITLE
Add liberapay for funding

### PR DESCRIPTION
**Pull request by MartinDelille**
This is just a proposal to create a new way to fund rambox through  https://liberapay.com/

The team https://liberapay.com/rambox should be create first.

Don't hesitate to ask me if you want more information about the system.

### CODE REVIEW

**Comment by Ash258** [comment]
I think there is no need new page for funding.

**Comment by MartinDelille** [comment]
I personnally use Rambox and would like to contribute. But I only use Liberapay for funding.

**Comment by MartinDelille** [comment]
up

**Comment by MartinDelille** [comment]
What is good with Liberapay is that it is a weekly donation (not one shot). You can get long term funding!

**Comment by saenzramiro** [comment]
Thank you @MartinDelille but we will continue with Fundraiseup. The donation link will be fixed in next release.

**Comment by MartinDelille** [comment]
I'm wondering why a project can't have multiple way to fund itself...

Anyway, I'll keep using Rambox without donating even if it is a nice software!

**Pull request closed without merging**
