### PR TITLE
Show notifications in new Gmail interface

### LINKED ISSUE #1649: No red dot notif for the new Gmail interface
### Steps to reproduce

1. add Gmail service
2. switch to new gmail interface

### Expected behavior

a red dot should be on the rambox icon whenever there's an unread email.

### Actual behavior

no red dot.

### ENVIRONMENT

> Rambox: v0.5.17

> OS: macOS High Sierra 10.13.4

> Arch: x64

### LINKED ISSUE #1659: Gmail unread count in Important : Others gets added as numbers.
### Steps to reproduce

1. Setup Gmail in Rambox
2. In Gmail, use "important" feature. Have some unread mails in both Important and Others
3. Check the unread count in Rambox tab and also in Rambox icon in windows task bar and in Rambox title bar.

### Expected behavior

Rambox should not add the 2 numbers. 

### Actual behavior

Rambox adds 2 numbers in Gmail tab and also in Icon in taskbar, in rambox title bar. 

### ENVIRONMENT

Windows. Latest Rambox downloaded on this date from Rambox.pro

> OS: Windows 

> Arch: x64 

Image: 
Tab unread count, title bar :
image

Task bar:
image

### PR DESCRIPTION
**Pull request by rzumstein**
closes #1649 
closes #1659

### CODE REVIEW

**Comment by rzumstein** [comment]
I added a commit to this to also close issue 1659 as well as 1649.


selection_008

**Comment by Ash258** [comment]
Add `notes` field, with info about Switching to new User interface. Until its default, then it could be removed.

**Comment by rzumstein** [comment]
That shouldn't be needed as this change will still show notifications in the old interface as well.

**Comment by gitofwebmobiledev** [comment]
When will be this new version 0.5.18 released as the production?

**Comment by StormPooper** [comment]
This will also include emails in the Spam folder, judging by the selector used. Would be nice to not count that in the total.

**Comment by StormPooper** [comment]
Realised you can hide the Spam folder under 'More' by dragging it. Should probably check if the element we're selecting is visible before adding it to the count (could check if the element has an `offsetParent` - if no, it's not visible). I'd create another pull request but I've had trouble setting the environment up.

**Comment by rzumstein** [comment]
@StormPooper have you tested it and verified that?  The selector should only be grabbing the top-most category, which is Inbox, and ignoring the others.

**Comment by StormPooper** [comment]
Apologies, as I said, I had trouble setting up the environment and this version hasn't been released yet. You're right though, re-reading it, it grabs the first element only, not all of them. My bad, disregard this.

**Comment by rzumstein** [comment]
No worries

**Pull request merged**
