### PR TITLE
Remove tracking

### LINKED ISSUE #1712: Amend privacy policy to inform users about tracking.
### Expected behavior
After reading the Privacy statement in README.md I was under the impression that rambox would not track my behavior. Looking through the sources I was saddened to see rambox accurately tracks my exact usage of the application. 

### Actual behavior
The user is being tracked outside of the defined scope. 

### ENVIRONMENT
Violating both European law and US. Not sure about other countries legal system.

---

Of course rambox does not require to hire a DPO to comply with GDPR. And there is no expectation that your data portability systems are of the same scope as bigger companies. However you should clearly inform users exactly what data is being gathered. 

Also make sure that your google analytics is configured to mask the last bit of the ip address. This helps anonymizing the gathered statistics while still revealing the demographic of your users. 
https://support.google.com/analytics/answer/2763052?hl=en.

### PR DESCRIPTION
**Pull request by TheGoddessInari**
The original project README says no personal information will be saved,
 but this level of analytics tracking is invasive, probably illegal, and
 not disclosed. Pull it.

closes #1712

### CODE REVIEW

**Comment by saenzramiro** [comment]
When we say "No personal information will be saved" regarding the services. Seems like we have to clarify more this.

The tracking helps us to know how many users used Rambox, which services, etc. This helps us to provide a better app. There is a feature request for adding an option to disable tracking that we must add it. Instead of removing the code, can you help us adding an option for disable it?

**Comment by saenzramiro** [comment]
Ok, so we will disable it by default but definitely needs to add an option and invite the user to help us by enabling it. What do you think?

**Comment by rodneyrod** [comment]
@saenzramiro That's how Mozilla do it with their browsers, when you open them up for the first time it asks if you want to send analytics back to them to help improve the product.
I think they do it enabled by default but that can be tweaked depending on what's more effective for this project.

**Comment by saenzramiro** [comment]
Ok, we will do something like that. I will close this PR because removing the code is not the solution.

**Pull request closed without merging**
