### PR TITLE
Add Android Messages service

### LINKED ISSUE #1723: Service Request: Android Messages
Google Announced support for android messages on the web.

This would be a nice extra service.

More info: https://messages.android.com/

### PR DESCRIPTION
**Pull request by carlosV2**
This PR adds the recently announced [Android Messages](https://messages.android.com/) service.

Note: There was a bit of a mess in the number of services so I counted the number of icons in the `resources/icons/` folder and I substracted 1 (for the custom one). Including this icon, there are a 100 of them.

Closes #1723

### CODE REVIEW

**Comment by Ash258** [comment]
Add "Closes #1723" into description.
No `js_unread`?

**Comment by carlosV2** [comment]
@Ash258 done.

I've been thinking that maybe we want it to be named `Android Messages` instead. What do you think?

**Comment by Ash258** [comment]
Also why so hard to extract unread count??
What will this give you?? `const unreadCount = document.querySelectorAll('.tpEAA.yrs5ff').length;`

**Comment by carlosV2** [comment]
@Ash258 selecting by CSS classes was my first thought but I wasn't sure if the name of the class was given by some sort of compilation or obfuscation code that could make the name to change esaily. This is the reason why I based the code on the CSS property instead.

I'm happy to put back the class-based method as per your suggest.

**Comment by saenzramiro** [comment]
Guys, I think that maybe the selector will fail in future releases because like @carlosV2 said, I think those classes are per compilation or obfuscation. Like Hangouts or others Google services, their classes changes.

We have to find a wait to get it without using CSS selectors.

**Pull request merged**
