### PR TITLE
New service: The Observable Forum

### PR DESCRIPTION
**Pull request by severo**
New service: the https://talk.observablehq.com/ forum (based on Discourse).

### CODE REVIEW

**Comment by Ash258** [comment]
No `js_unread`? Why? Page doesn't support some count of unread messages?

**Comment by severo** [comment]
I understand that it shows the unread messages without the need to fill js_unread. I created a custom service without filling this field, and it shows me the number of unread messages. Maybe there is something I didn't get, if so, please let me know.

**Comment by saenzramiro** [comment]
Thank you @severo but Observable is not an "Email" or "Messaging" app.

**Comment by severo** [comment]
Yes, you're right... I misunderstood the goal of the Rambox project. I use it personally for everything that provides me with notifications, that includes forums.

**Pull request closed without merging**
