### PR TITLE
Added search in page feature

### LINKED ISSUE #242: [Feature Request] Search within a webpage (find bar)
With a find bar, you can search for text inside pages (messages etc.).

Just like CTRL+F in web browsers.

### PR DESCRIPTION
**Pull request by maxerbox**
Finally, it is added.
image

Closes #242

### CODE REVIEW

**Comment by Redirts** [comment]
The find option should be added to the Edit menu

**Comment by saenzramiro** [comment]
@Redirts Yes, you are right. Will add it.

**Comment by Redirts** [comment]
Also, the find field should be automatically selected so we can start typing whatever we are looking for. Currently we have to click on the find field first.

**Comment by maxerbox** [comment]
> Also, the find field should be automatically selected so we can start typing whatever we are looking for. Currently we have to click on the find field first.

You should open an issue for it

**Pull request merged**
