### PR TITLE
Fix/electron update 3.1.3

### LINKED ISSUE #2019: Whatapp
https://web.whatsapp.com/ 
adding this custom service, does not work!

	
	-
	> Rambox 0.6.3
	> Electron 2.0.14
	> win32 x64 6.3.9600

### LINKED ISSUE #2064: Slack will require Chromium 66 or later after March 15
Slack has made it known that they're bumping up their [minimum browser requirements](https://get.slack.help/hc/en-us/articles/115002037526) as of March 15. They're going to require Chrome 66 or later.

### ENVIRONMENT

> Rambox: v0.6.3

> OS: macOS 10.12.6

> Arch: x64

### LINKED ISSUE #2076: Threema Web: "This browser is not supported"
### Steps to reproduce

1. Open Threema Web in Rambox

### Actual behavior
"This browser is not supported

Please use the latest version of Google Chrome, Mozilla Firefox, Opera or Safari (iOS only), otherwise the web client might not work properly."

### ENVIRONMENT

> Rambox: v0.6.3

> OS: Linux Mint 19 Tara

> Arch: x86_64

### LINKED ISSUE #2079: Use updated version of skype for web
When I open the skype it shows 'Support for this version of Skype for Web is coming to an end. A new preview version is available now for Microsoft Edge and Google Chrome with HD video calling, call recording and much more. Try it out'.
The app should  use the updated version of skype for web.

### Steps to reproduce

1. Add skype service
2. Try to open the skype
3. Warning message is shown

### Expected behavior

The app should be using the updated version of skype for web

### Actual behavior

The app is using an outdated version of skype for web

### ENVIRONMENT

> Rambox: v 0.6.3

> OS: Ubuntu 18.04

> Arch: x64 

Electron: 2.0.14
Chromium: 61.0.3163.100
Node: 8.9.3

### LINKED ISSUE #2100: Slack is complaining 3rd party tool (Rambox) is not up-to-date
Slack is saying Rambox is not using the updated version.
I'm using version 0.6.3 but seems, internally, that Rambox is not updating the APIs of Slack.

image

	
	-
	> Rambox 0.6.3
	> Electron 2.0.14
	> win32 x64 10.0.17763

### PR DESCRIPTION
**Pull request by maxerbox**
Updated electron version to 3.1.3.
I followed the breaking API changes for 3.0.
image

Fixes #2100 
Fixes #2079 
Fixes #2076 
Fixes #2019 
Fixes #2064

### CODE REVIEW

**Comment by manuel-uberti** [comment]
This can possibly fix the GTK issue described here: https://github.com/lassekongo83/amber-theme/issues/14

**Comment by claui** [comment]
This will also fix #2064.
Mind that there’s only two days left to help keep Slack compatible with Rambox.

@saenzramiro What can we do to help get this PR merged?

**Comment by Mte90** [comment]
yes please, the alerts are very annoying...

**Comment by jeensg** [comment]
Does anyone know where recent changes are published? Is there a preview of another branch or something? Electron is now with version 4...but I don't find any hint if somebody is working on updating rambox ... +1 alerts are ynoying, more worrying about slack not working starting tomorrow...

**Comment by maxerbox** [comment]
If you would like to test it, I merged every open pull requests and made a build : 
https://github.com/maxerbox/community-edition/releases/tag/untagged-fe944ef70a27f5c75470

**Comment by jeensg** [comment]
Thanks for your work!
Do you know anything about a possible version from @ramboxapp, are they still developing? dDon't see any people anymore. Seems a little dead :-( and I don't see who is developing what here ... to what extend and so on. There seems to be only one person contributing? Your pull-requests don't seem to be approved neither!?

**Comment by jeensg** [comment]
Sorry for writing so many questions :-) I do get it: 4 milestones for version 0.6.4, 1 is closed with comment "wontfix", mpf, the opthers open since January, hehe, let's see, it's still "time"...

**Pull request merged**
