### PR TITLE
Front End Updates & New Theme

### PR DESCRIPTION
**Pull request by NickMcSweeney**
#### Major Changes
 * added a new 'dark' theme
 * added theme selection to preferences menu

#### Minor Changes
 * changed to notification counter method to prevent non numerical characters (slack was having issues with a 'dot' displaying if there were no notifications).
 * made is so only one icon displayed in search bar at a time.
 
##### Additional Notes:
 * As far as I know there isn't a good way to build out multiple themes in Ext-js, so you have to build and then move them to the resources folder. In testing the process that I have used is:
    - change the `app.json` to the 'new' theme & build.
    - get the newly built `Rambox-all.css` file out of the `build` folder system.
    - move the file into the resources folder and rename to `Rambox-`{THEME_NAME}`.css`
    - change the theme name back in the `app.json` and rebuild.

##### Personal Notes:
Hello,
Since this is the first time I am contributing to this, my name is Nick, and I think Rambox is pretty awesome. These are just some tweaks that I've made that fix things that I have issues with/make things look more like what I like. I thought that you may appreciate the opportunity to include them.

This is the first time I have touched Ext-js/Sencha (I normally work Vue-js) so I apologise if there is anything that is wrong or in an incorrect style, and am happy to have feedback if you like the change but would prefer the code in a different format or something like that.

Anyways I'm just making changes as I notice things that bother me. If you like the changes please add it in, if there are things that you wish i would have included let me know, if you have no interest using my changes that's cool too. 

hope that there's something helpful in here.
Nick

### CODE REVIEW

**Comment by saenzramiro** [comment]
Awesome! Thank you Nick!

**Comment by JulioSDDR** [comment]
Cant wait util it is merged...

**Comment by saenzramiro** [comment]
I'm having difficulties to run the app in dev mode and also building for production. It's showing me a lot of 404 errors trying to load external resources like fonts, images, etc.

We will need to fix this and also, prevent Rambox to slices images because slices are for IE and we don't need that.

Can anyone help with this?

**Comment by taylorjdawson** [comment]
Hey! Really nice work guys. @NickMcSweeney theme selection is something that I have been looking forward too. I don't know if you are planning to do this already but it would be nice to remove the traditional windows menu buttons and create a custom more aesthetic menu system. For example, something like the [Hyper terminal](https://hyper.is).

Thanks again for what you guys are doing!

**Comment by vraravam** [comment]
@NickMcSweeney - would you be able to resolve the conflicts and resubmit? As an avid user of Rambox, having this in the community edition would be greatly appreciated.

**Pull request closed without merging**
