### PR TITLE
enable gmail labs

### PR DESCRIPTION
**Pull request by iliu**
to fix https://github.com/saenzramiro/rambox/issues/1684

### CODE REVIEW

**Comment by JakobStruye** [comment]
Would that reintroduce #1495 ?

**Comment by iliu** [comment]
not too sure, i wasn't aware of #1495, but it sees weird that gmail labs was the culprit for it.

**Comment by JakobStruye** [comment]
Have you been using Gmail with Labs enabled as a custom service by any chance? If you do and haven't experienced that issue it definitely wouldn't be a problem.

**Comment by iliu** [comment]
thanks i'll give it a shot.

**Comment by lehippie** [comment]
I've been using Gmail with labs enabled as a custom service for 2 months now. I'm using "preview pannel" and "unread count" and I've not seen any refresh issue.

**Pull request merged**
