### PR TITLE
Feature: Override User-Agent for all services

### PR DESCRIPTION
**Pull request by ozskywalker**
Added to support feature request #440

### CODE REVIEW

**Comment by ArmeF97** [comment]
please merge this

**Comment by saenzramiro** [comment]
Thank you for this PR.

What's the idea of this? What are the benefits?

**Comment by ozskywalker** [comment]
In corporate environments where it may be necessary to set a custom User-Agent to satisfy internal security requirements, setting a custom User-Agent one service at a time is taxing on the user.

This PR creates a single, global override option to save power users time from manually configuring each chat service in order to use Rambox within their environment.

Based off feature request https://github.com/ramboxapp/community-edition/issues/440

**Comment by emilient** [comment]
This merge is important, if you use Microsoft Teams you will discover that's  ot possible to call with rambox or any other browser than IE ; if you change the user agent, it works with any browser, so it should work with rambox wich could become the first tools that allow to use Teams on Linux.

**Comment by TommasoDb** [comment]
Is important for our company too: same problem with MS Teams on Linux

**Pull request merged**
