### PR TITLE
Optimize PNG images via Google's zopflipng

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Use Google'z zopflipng to re-compress the png images losslessly!

2336 png images optimized as below and about 1.3MB saved!
https://pastebin.com/raw/Vsd1Nxv2

### CODE REVIEW

**Comment by saenzramiro** [comment]
Sounds interesting, but can you compress only the images inside *resources* folder? Because all the others are from the SDK of Ext JS and I don't want to modify them, I want to keep SDK original.

**Comment by PeterDaveHello** [comment]
Fair enough, doing now.

**Comment by PeterDaveHello** [comment]
@saenzramiro what about these two files?

`packages/local/rambox-default-theme/resources/images/toolbar/main-more.png`
`packages/local/rambox-default-theme/resources/images/toolbar/newversion-more.png`

**Comment by PeterDaveHello** [comment]
Ping @saenzramiro

**Pull request closed without merging**
