### PR TITLE
Enable video chat in ms teams

### LINKED ISSUE #1292: Video call is not allowed in Teams
### Steps to reproduce

1. Open Teams on Rambox
2. Try a video call

### Expected behavior

The video call button should be enabled and allow starting a video call.

### Actual behavior

The video call button is disabled; a tooltip says video is not yet supported in my browser.

### ENVIRONMENT

Version: 0.5.13
Platform: darwin (x64)
Electron: 1.7.8
Chromium: 58.0.3029.110
Node: 7.9.0

### LINKED ISSUE #1829: Video in MS Teams does not work
When using Microsoft Teams, there is the option to use video.  But when I click on the video icon, it says, "Video is not supported in your browser"
	-
	> Rambox 0.5.17
	> Electron 1.8.4
	> win32 x64 6.1.7601

### PR DESCRIPTION
**Pull request by brad**
Use an Edge browser user string to enable video chats. Tested on Antergos Linux

- Closes #1292 
- Closes #1829

### CODE REVIEW

**Comment by Laxen** [comment]
Quick question: Can you mention someone (type @ and then their name) and still write things after the mention without it disappearing? The mention disappears for me (name goes from blue to regular black) whenever I type something after the mention. I've found this happens whenever I use Edge as the user agent.

For example type this (replace "name" with an actual name in your team):
@name hello there!

**Comment by brad** [comment]
@Laxen I don't see that issue. To make sure I understand you correctly, say there is a user named "Homer J Simpson", if I type `@Homer J Simpson hello there!` it works, not if I type `@homer hello there!`
I never have done it that way though, so I can't say whether it worked that way before or not. I usually just type the first few chars and the `<TAB>` or `<Enter>` to select the user I want to mention

**Comment by Laxen** [comment]
Yes that is exactly the way I'm doing it. I start typing the name then <Enter> to select the user and their full name appears in the text box in blue color. Then I press <Space> because I want to write a message after the name, and after ~0.5 seconds the color of the name turns into the same color as regular text. When I send the message it's no longer a mention, it's just regular text. 

However I just noticed that after you press <Enter> to get the users full name in your text box, you can then quickly type a message and the mention will stay (everything you type will become blue). However if you pause for ~0.5 seconds the text will turn into regular text and it won't be a mention anymore. 

I have the exact same problem in another client (teams-for-linux) when I add Edge to user agents. Calls work, but mentions break. But it's strange if you don't have the same problem, that suggests there's something else going on...

**Comment by brad** [comment]
Sorry @Laxen I stand corrected. I experience the same thing you describe when running Teams from this branch. I don't experience that issue however when using the workaround posted [here](https://github.com/ramboxapp/community-edition/issues/1292#issuecomment-431418444) with Rambox 0.6.1 😖 I am flummoxed as to what is going on here, do you have any ideas?

**Comment by Laxen** [comment]
Running your workaround code works for me too (I get normal mentions and calls are enabled). I dived into the Rambox source to find out when the "custom code" is executed and found the following:

1. [Line 68 in AddController.js ](https://github.com/ramboxapp/community-edition/blob/master/app/view/add/AddController.js#L68) checks if there's something in the "custom code" box (called `js_unread`) when editing the configs for a service, and if so it asks to reload the service by calling `view.reloadService()`.
2. `view.reloadService()` is defined at [line 591 in WebView.js](https://github.com/ramboxapp/community-edition/blob/master/app/ux/WebView.js#L591). All it does is basically call `webview.loadURL()` to reload the URL.
3. At [line 409 in WebView.js](https://github.com/ramboxapp/community-edition/blob/master/app/ux/WebView.js#L409) an EventListener is defined for "dom-ready". When this event fires it will read `js_unread` (aka the custom code box) and inject it, together with some other scripts, using `webview.executeJavaScript()`. 

I've tried injecting your script at other places but none seem to work, for some reason it needs to be injected when the "dom-ready" event fires or we get the problem with mentions. I have very little knowledge of Electron and JavaScript so I can't really explain why without reading up on it. 

I can also mention that I hacked this into teams-for-linux and it works in the same way there as well. Which means I can get it to work there by adding the "dom-ready" listener and using your code. Awesome!

**Comment by brad** [comment]
@Laxen Thank you for the insight! I have adjusted to PR to take the "workaround" solution (adjust user agent after dom ready) and embed it into the app. If you wouldn't mind checking that it works for you too, I would appreciate that a lot

**Comment by Laxen** [comment]
Seems to work well, both mentions and calls work perfectly with this fix now! Didn't see that other services modified js_unread in that list before, that is a neat solution.

**Comment by saenzramiro** [comment]
Thank you!

**Pull request merged**
