### PR TITLE
Edited gmail notification check

### LINKED ISSUE #1999: unread alarm in Gmail does not appear
### Steps to reproduce

1. Unread notification does not appear on gmail despite unread mail exist.
2. It can be fixed by modifying gmail's js_unread in app/store/ServicesList.js

### Expected behavior

expected

### Actual behavior

unexpected

### ENVIRONMENT

> Rambox: v0.6.3

> OS: Ubuntu 16.04 LTS

> Arch: x64

### LINKED ISSUE #2017: 0.6.3 not showing badges for mail
currently have my gmail attached, since the update the notification badges do not appear.
other badges working as intended.

	
	-
	> Rambox 0.6.3
	> Electron 2.0.14
	> win32 x64 10.0.17134

### LINKED ISSUE #2032: Still no unread badge gmail
### Steps to reproduce

1. Close and re-open Rambox
2. Refresh and change notification settings, turning off and then back on badge notifications
3. Check 'Show notifications', 'Display tab unread counter', 'Include in global unread counter'
4. Click 'Edit [gmail name]'
5. Confirm using most up-to-date Rambox

### Expected behavior

Rambox shows unread badge when receiving new unread emails in Gmail

### Actual behavior

No unread badge shows when unread messages arrive

### ENVIRONMENT

> Rambox: v0.6.3

> OS: MacOS Mojave 10.14.2 (18C54)

> Arch: x64

I've seen many threads about this, but none seem to have clear instructions for fixing this issue for n00bs like myself! Is it not already integrated into the new update to fix this?

### PR DESCRIPTION
**Pull request by maxerbox**
now parsing from title

Fixes #2032 
Fixes #1999 
Fixes #2017

### CODE REVIEW

**Comment by maxerbox** [comment]
code: `function checkUnread(){var t=document.title.match(/\(([\d ]+)\)/);updateBadge(t?parseInt(t[1].replace(/[^0-9]/, '')):0)}function updateBadge(e){1<=e?rambox.setUnreadCount(e):rambox.clearUnreadCount()}setInterval(checkUnread,3e3);`

**Comment by lhalman** [comment]
Sorry, n00b here — where do I add this code to address this situation? Thanks so much for posting and bringing all these together!

**Comment by lhalman** [comment]
> Sorry, n00b here — where do I add this code to address this situation? Thanks so much for posting and bringing all these together!

I realized where to add this code, for n00bs!

In the main Rambox "Add a service" window, look at the "enabled services" list on the and right click the gear icon next to the service you wish to modify. At the bottom of the dialog that pops up, you'll see "Advanced" and you'll see the box to add custom code. Paste the code above and then click "Edit [name of service]" and it will say it needs to restart the service to apply the code. Click 'yes' and then you should see the notifications no problem!

Hope this works!

**Comment by MrObvious** [comment]
Thanks. This works now.

**Comment by maxerbox** [comment]
Ps: since gmail is not displaying the unread message count in title while you are reading messages, the unread message counter disappears when you open a mail

**Comment by bchanudet** [comment]
Hi,

I encountered this very bug today, and did work a little bit according to the code you posted on January 2nd and your last comment (the lack of notification annoyed me because I'm used to let Rambox open on the last e-mail).

Idea is to get the number from the badge displayed on the Inbox, as for accessibility they add the number in the ARIA label attribute.

Here is the code: 

```javascript
function checkUnread(){
    var t=document.querySelectorAll("a[href$=inbox][title=Inbox]")[0].getAttribute("aria-label").match(/([0-9]+) unread/);
    updateBadge(t?parseInt(t[1].replace(/[^0-9]/, '')):0)
}
function updateBadge(e){ 
    1<=e?rambox.setUnreadCount(e):rambox.clearUnreadCount()
}
setInterval(checkUnread,3e3);
``` 

It might not work for languages other than English because of the selection on the `title` attribute and the check on the `unread` string in the regexp. But it's a base on which we can look to improve Rambox's behaviour with Gmail. :)

**Comment by maxerbox** [comment]
Yep, and also that's counting all the messages (social, notifications...).

**Comment by martin-g** [comment]
Just updated to 0.6.6 and again there is no unread messages counter for GMail.

**Comment by cshivakumar** [comment]
hi im Cshivakumar im India Telangana Hyderabad nampally 500012 gowliguoda chaman 15-3-238

**Comment by maxerbox** [comment]
I'm still using this:
```
function checkUnread(){var t=document.title.match(/\(([\d ]+)\)/);updateBadge(t?parseInt(t[1].replace(/[^0-9]/, '')):0)}function updateBadge(e){1<=e?rambox.setUnreadCount(e):rambox.clearUnreadCount()}setInterval(checkUnread,3e3);
```
It is still working with it.

**Comment by martin-g** [comment]
Thank you, @maxerbox ! This works indeed!

**Comment by beledouxdenis** [comment]
The problem when using the title is that, if you change of label, and forgot to get back to the inbox when you leave Rambox, you no longer have the unread counter working, as it now counts the unread of the current label rather than the main inbox.

Besides, when you go in your spams and you have a lot of them, you suddenly have a high counter.

I personally better like:
```javascript
function checkUnread(){
  var e=document.getElementsByClassName("aim")[0].getElementsByClassName('bsU');
  updateBadge(e.length ? parseInt(e[0].innerText) : 0);
}
function updateBadge(e){
  1<=e?rambox.setUnreadCount(e):rambox.clearUnreadCount();
}
setInterval(checkUnread,3e3);

```
which can be shortened:
```javascript
function checkUnread(){var e=document.getElementsByClassName("aim")[0].getElementsByClassName('bsU');updateBadge(e.length ? parseInt(e[0].innerText) : 0);}function updateBadge(e){1<=e?rambox.setUnreadCount(e):rambox.clearUnreadCount();}
```
This way it gives the unread count of the main inbox, even when you change of label.

**Pull request merged**
