### PR TITLE
Changed js_unread function for service discord

### LINKED ISSUE #1730: No tray icon change or red asterisk for Discord tabs (even though notifications work fine)
### Steps to reproduce

1. Add Discord to Rambox.
2. Enable Discord notifications.
3. Select a different tab in Rambox and switch to a different application.
4. Get a Discord notification.

### Expected behavior

The tray icon should turn red and the Discord tab in Rambox should get a red asterisk (like it does for other services).

### Actual behavior

Neither of these things happen, even though notifications themselves popup.

### ENVIRONMENT

> Rambox: v0.5.17
> OS: Pop!_OS (Ubuntu variant from System 76)
> Arch: x64

From `Help -> About`:

```
Version: 0.5.17
Platform: linux (x64)
Electron: 1.8.4
Chromium: 59.0.3071.115
Node: 8.2.1
```

### LINKED ISSUE #1801: Discord badge updates aren't reliable
### Steps to reproduce
Load Discord with unread server tabs or unread badges/mentions.

### Expected behavior

Discord alerts function normally.

### Actual behavior

Discord doesn't alert, and can show nothing on the tab even with many indirects on different servers.

### ENVIRONMENT

> Rambox: v0.5.17

> OS: Windows 10

> Arch: x64

This is because the js_unread is using the 'unobfuscated' class names, while Discord has been using obfuscated class names. It's only *sometimes* picking anything up via [class^="nameUnreadText-"].

### PR DESCRIPTION
**Pull request by maxerbox**
In order to be functional, it will count only the unread dms (less cancerous, because of the everyone mentions). It should also work even if the class names are updated

- Closes #1801 
- Closes #1730

### CODE REVIEW

**Comment by Ash258** [comment]
Just use this as custom code:

```javascript
function getAlertCount(e) {
	for (var t = 0, a = 0; a < e.length; a++) {
		var r = e[a];
		if (r && r.childNodes && 0 < r.childNodes.length) {
			var d = parseInt(r.childNodes[0].nodeValue, 10);
			t += d.isNaN
				? 1
				: d
		} else {
			t++
		}
	}
	return t
}
function checkUnread() {
	var e = 0;
	dms = document.querySelectorAll("[class*=dms]")[0].querySelectorAll("[class*=wrapper][class*=badge]"),
		updateBadge(0, e += getAlertCount(dms))
}

function updateBadge(e, t) {
	rambox.setUnreadCount(t)
}

setInterval(checkUnread, 3e3);
```

**Comment by Ash258** [comment]
@maxerbox That code is missing clearing unread count. Also that dms variable look weird.
What does `document.querySelectorAll("[class*=dms]")[0].querySelectorAll("[class*=wrapper][class*=badge]")` do? Calling querySelectorAll on some htmlnode is legit?? Have you tested that code?

**Comment by maxerbox** [comment]
Well, it's working. It's clearing itself since it call the unread count function with 0, same as clearUnreadCount

**Comment by gwillen** [comment]
How does one get the (•) badging to work when there are unread messages that are not direct messages? I have code for this, but I can't figure out from an inject_js snippet how to set the badge to display (•). I am working around it right now by setting the count to (-1), but this does not cause the global badge to display a (•).

**Comment by queicherius** [comment]
I use this code to show unread DMs + server mentions as `(123)` and unread servers as `(•)`:

```js
function parseBadges (badges) {
  return Array.from(badges).map(x => parseInt(x.innerText, 10)).reduce((a, b) => a + b, 0)
}

function checkForUnread () {
  const unreadDMs = parseBadges(document.querySelectorAll(`[class*='wrapper-'][class*='badge-']`))
   + parseBadges(document.querySelectorAll(`[class*='contentUnreadText-'] [class*='wrapper-']`))
  const unreadServers = document.querySelectorAll(`[class*='guild-'][class*='unread-']`).length
    + document.querySelectorAll(`[class*='contentUnreadText-']`).length

  updateBadge(unreadDMs, unreadServers)
}

function updateBadge (dms, servers) {
  let change = ''
  if (servers > 0) change = '(•)'
  if (dms > 0) change = `(${dms})`

  document.title = ORIGINAL_TITLE + ' ' + change
}

// Setup the check interval
const ORIGINAL_TITLE = document.title
setInterval(checkForUnread, 1000)
```

**Comment by queicherius** [comment]
@gwillen That might be because I do not use the "official" `Discord` service, but the `_Custom Service`? Not quite sure.

**Comment by dikamilo** [comment]
Merged changes count only dms, if you want to count unread servers then this version will work:

`
function getAlertCount(e) {
    for (var t = 0, a = 0; a < e.length; a++) {
        var r = e[a];
        if (r && r.childNodes && 0 < r.childNodes.length) {
            var d = parseInt(r.childNodes[0].nodeValue, 10);
            t += d.isNaN ? 1 : d
        } else t++
    }
    return t
}

function checkUnread() {
    var counter = 0;
    dms = document.querySelectorAll("[class*=dms]")[0].querySelectorAll("[class*=wrapper][class*=badge]");

    counter += getAlertCount(dms);
    counter += document.querySelectorAll("[class*=guild][class*=unread]").length;
    counter += document.querySelectorAll("[class*=guild]")[0].querySelectorAll("[class*=wrapper][class*=badge]").length;

    updateBadge(0, counter);
}

function updateBadge(e, t) {
    rambox.setUnreadCount(t)
}

setInterval(checkUnread, 3e3);
`

**Pull request merged**
