### PR TITLE
Change Linux category from Utility+Office to Network

### PR DESCRIPTION
**Pull request by qoheniac**
I think Rambox fits better in Network than in Utility+Office.

### CODE REVIEW

**Comment by saenzramiro** [comment]
I think _Network_ is related to apps for monitor the network or similars.

**Comment by qoheniac** [comment]
Here you can find the specifications: https://specifications.freedesktop.org/menu-spec/latest/apa.html#main-category-registry

**Comment by Mte90** [comment]
any news for that?

**Comment by joe776** [comment]
The additional categories especially list InstantMessaging as related to Networking:
https://specifications.freedesktop.org/menu-spec/latest/apas02.html

So changing to that should be correct.

**Comment by Mte90** [comment]
and it's me after an year for a ping

**Comment by saenzramiro** [comment]
Ok, let's change it to Network.

**Pull request merged**
