### PR TITLE
New icons design

### LINKED ISSUE #800: Mac icon replacement
I wasn't feeling the not-full-native look of the icon on macOS and I decided to tweak it a little. Showing what I came up with just in case anyone else is interested.

I can share the .icns files and/or open a PR if you'd want to include it.

captura de pantalla 2017-04-13 a las 17 15 07

### PR DESCRIPTION
**Pull request by hacknug**
I added the Sketch source file with both versions of the icon I designed and the old one. I've also created the .icns versions for macOS.

Should I do the same for .ico and .png? Should I tweak my design so it looks more native for Windows and Linux?

Let me know how you'd like me to proceed with this.

Closes #800.

### CODE REVIEW

**Comment by nmat** [comment]
@hacknug is it possible to also get them in greyscale? I believe that there is options for greyscaling in mac os x and also linux for this? (thinking dark mode themes) 

@saenzramiro or am I wrong?

**Comment by hacknug** [comment]
I can add a grayscale version, would that work? But doesn't dark mode in macOS only affect menu bar apps?

**Comment by nmat** [comment]
Not 100% sure to be honest.

**Comment by saenzramiro** [comment]
Yes, for macOS we don't add a Rambox icon in menu bar, only in dock bar. For this needs to be colored.

But for Linux and Windows, we use system tray. My idea is to create tray icons for this OS following the styles. For example, in Windows 10 the tray icon needs to be like:

image

ICO and PNG are welcome also! 😉

**Comment by hacknug** [comment]
I'll get to it later today or tomorrow. Will keep you updated ✌️️✨

**Comment by hacknug** [comment]
Do you guys know the specs for those tray icons in Windows? I've been going through their docs and couldn't find it. I guess they should be drawn in their 32×32 pixel grid and packed in a .ico file (with some bigger sizes included), right?

https://docs.microsoft.com/en-us/windows/uwp/style/icons
https://docs.microsoft.com/en-us/windows/uwp/controls-and-patterns/tiles-and-notifications-app-assets

**Comment by nmat** [comment]
Very nice! good job!

**Comment by saenzramiro** [comment]
No, right now we are using [256x256 pixels image](https://raw.githubusercontent.com/saenzramiro/rambox/master/resources/Icon.ico) but a 32x32 pixels should be ok (https://github.com/electron/electron/issues/2248#issuecomment-122040241).

**Comment by hacknug** [comment]
Sorry for the hiatus, guys, but I've been kinda busy lately. I just finished with the tray icon after being able to build a desktop computer yesterday 😄 

I have two versions of the icon, one with full opacity and another one at 50%. Some apps use outline/filled versions depending on whether the app has unread notifications or something. Some other apps use opacity to convey the same thing.

Since the icon has a lot of detail in it, the outline version didn't work well and I decided to go the opacity way.

Are we gonna update the app to show both states of we'll just use the one?

**Comment by nmat** [comment]
question: how would this icon affect getting a notification or to have unread messages. Will it still be red on unread messages?

**Comment by hacknug** [comment]
@nmat if your question is about Windows, what I'm proposing is to change the icon's opacity instead of changing colors to make it feel more native. Most system icons do that and since things like outline/fill wouldn't work, I think it's the best solution.

Here's a screenshot of how both states would look like:

captura de pantalla 2017-06-05 a las 14 06 53

I tried building the app just so I could see how it would look like but I couldn't get it done. Maybe @saenzramiro might help me out with this or make a build for testing.

Also, is there anything we should work on for Linux?

**Comment by nmat** [comment]
@hacknug thank you. I compared this with how for example slack uses it. Maybe this can be configured in some way?

In slack for example you have a blue dot on the upper right corner, almost like the red number inside rambox. Maybe this would be a good idea? Not 100% sure. @saenzramiro what do you think?

**Comment by hacknug** [comment]
A notification dot sounds also good to me. Let me check it out tomorrow whenI can use my desktop computer and I'll get back to you. I think it might be even better because the opacity thing makes it look like its disabled or something.

**Comment by saenzramiro** [comment]
We will need to see what option is better, but in my opinion, I prefer a dot in a corner of the icon. Something like Notification Center icon of Windows 10.

**Comment by hacknug** [comment]
Do we need to make the icon with the dot as a sepparate icon or that would be added by the app on top of the regular icon?

Let me know what is it that you need me to do and I'll probably be able to get it done in a day or two.

**Comment by qoheniac** [comment]
I am using the TopIcon Plus GNOME Shell extension so that the Rambox icon shows up in GNOME's top panel. Therefore a monochrome icon would be a really nice thing. Changing the opacity when there are messages would be a bit uncommon for GNOME I think. The idea with the dot sounds really good.

**Comment by saenzramiro** [comment]
@hacknug I think we can add the dot by code.

**Comment by hacknug** [comment]
@saenzramiro cool. So is there anything else that you need me to do? Also, can you make a build for Windows so I can test how it looks like? (I wasn't able to build it myself when I tried from by desktop computer and now it's dead and will be for a few more days/weeks).

**Comment by aSugarRush** [comment]
The idea of a monochrome icon is really good in my opinion, and I would like to have it right now.

I think the best option would be to change the transparency, this way it would seem more native than with a red dot, but maybe it will not be noticed when you have an unread message.
Maybe a mix of both, why not?

**Comment by hacknug** [comment]
Can anyone make a Windows build so we can make sure everything works and looks okay?

**Comment by nmat** [comment]
This topic should probably change to New icon design or something since it is not just for MacOS

**Comment by hacknug** [comment]
@nmat done!

Can anyone make a Windows build so we can make sure everything works and looks okay? For some reason I can't build it myself on my MacBook.

**Comment by saenzramiro** [comment]
I will do it ASAP and report it here.

Thank you @hacknug for your work!

**Comment by niosus** [comment]
Hey guys, is there any progress on this? I would love to see the new icon :)

**Comment by Lvaskz** [comment]
Yes, I am interestelar too😁

**Comment by hacknug** [comment]
As far as I know, Ramiro is planning on adding them to the new version he's been working on for a while. In the meantime you could download the files on this PR and swap them for the ones the app uses 😉

**Comment by exetico** [comment]
Please also consider a better tray-icon for us Mint users :-D (+ Ubuntu)

**Pull request closed without merging**
